<a href="https://colab.research.google.com/github/ApahSaroj/WQC/blob/main/Ensemble_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://github.com/ShapeAI/-REVIEW-Ensemble-Learning/blob/master/Ensemble%20Learning.ipynb

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
df = pd.read_excel('/content/drive/MyDrive/DATA/WQC_test.xlsx')
df.drop(df.columns[df.columns.str.contains('unnamed',case = False)],axis = 1, inplace = True)
#df.drop(df.columns[df.columns.str.contains('WPI',case = False)],axis = 1, inplace = True)
df.drop(df.columns[df.columns.str.contains('WQC',case = False)],axis = 1, inplace = True)
df

       pH   DO    TDS  Alkalinity  ...   Nitrate    Sulphate  Phosphate       WPI
0    8.14  8.7   84.0        52.0  ...  0.758000    6.534660    0.06211  0.249528
1    7.70  8.8  110.0        76.0  ...  0.196062    8.138620    0.00960  0.216400
2    7.60  7.5   75.0        44.0  ...  0.298875    3.855625    0.01280  0.183814
3    8.20  9.1   76.0        56.0  ...  0.299590    2.238750    0.01536  0.219282
4    7.31  7.3   84.0        52.0  ...  0.106000    5.600000    0.01000  0.165831
..    ...  ...    ...         ...  ...       ...         ...        ...       ...
482  7.60  5.6  224.0         8.0  ...  1.352000  104.480000    0.01500  0.419630
483  7.30  5.6  266.0        96.0  ...  7.074000   61.068000    0.03300  0.432996
484  5.10  5.8  290.0        12.0  ...  9.256000   89.910000    0.16300  0.326811
485  7.40  6.4  230.0        72.0  ...  7.110435   48.500000    0.21900  0.509970
486  7.60  6.9  243.0        68.0  ...  6.385000   59.940000    0.07000  0.422551

[487 rows x 15 columns]

In [4]:
def quality_check(num):
    s= ''
    if num <=0.5 :
        s='Suitable'
    elif num > 0.5:
        s='Unsuitable'
    return s

In [5]:
df['WQC']=df['WPI'].apply(quality_check)
df

       pH   DO    TDS  Alkalinity  ...    Sulphate  Phosphate       WPI         WQC
0    8.14  8.7   84.0        52.0  ...    6.534660    0.06211  0.249528    Suitable
1    7.70  8.8  110.0        76.0  ...    8.138620    0.00960  0.216400    Suitable
2    7.60  7.5   75.0        44.0  ...    3.855625    0.01280  0.183814    Suitable
3    8.20  9.1   76.0        56.0  ...    2.238750    0.01536  0.219282    Suitable
4    7.31  7.3   84.0        52.0  ...    5.600000    0.01000  0.165831    Suitable
..    ...  ...    ...         ...  ...         ...        ...       ...         ...
482  7.60  5.6  224.0         8.0  ...  104.480000    0.01500  0.419630    Suitable
483  7.30  5.6  266.0        96.0  ...   61.068000    0.03300  0.432996    Suitable
484  5.10  5.8  290.0        12.0  ...   89.910000    0.16300  0.326811    Suitable
485  7.40  6.4  230.0        72.0  ...   48.500000    0.21900  0.509970  Unsuitable
486  7.60  6.9  243.0        68.0  ...   59.940000    0.07000  0.422551    Suitable

[487 rows x 16 columns]

In [6]:
df.drop(df.columns[df.columns.str.contains('WPI',case = False)],axis = 1, inplace = True)
df

       pH   DO    TDS  Alkalinity  ...   Nitrate    Sulphate  Phosphate         WQC
0    8.14  8.7   84.0        52.0  ...  0.758000    6.534660    0.06211    Suitable
1    7.70  8.8  110.0        76.0  ...  0.196062    8.138620    0.00960    Suitable
2    7.60  7.5   75.0        44.0  ...  0.298875    3.855625    0.01280    Suitable
3    8.20  9.1   76.0        56.0  ...  0.299590    2.238750    0.01536    Suitable
4    7.31  7.3   84.0        52.0  ...  0.106000    5.600000    0.01000    Suitable
..    ...  ...    ...         ...  ...       ...         ...        ...         ...
482  7.60  5.6  224.0         8.0  ...  1.352000  104.480000    0.01500    Suitable
483  7.30  5.6  266.0        96.0  ...  7.074000   61.068000    0.03300    Suitable
484  5.10  5.8  290.0        12.0  ...  9.256000   89.910000    0.16300    Suitable
485  7.40  6.4  230.0        72.0  ...  7.110435   48.500000    0.21900  Unsuitable
486  7.60  6.9  243.0        68.0  ...  6.385000   59.940000    0.07000    Suitable

[487 rows x 15 columns]

In [7]:
print(df.isnull().sum())

pH            0
DO            0
TDS           0
Alkalinity    0
EC            0
Na            0
Ca            0
Mg            0
K             0
F             0
Cl            0
Nitrate       0
Sulphate      0
Phosphate     2
WQC           0
dtype: int64

In [8]:
df = df.dropna()

In [9]:
#importing required libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
import warnings
warnings.filterwarnings('ignore')

In [10]:
data = df
data.head()

     pH   DO    TDS  Alkalinity  ...   Nitrate  Sulphate  Phosphate       WQC
0  8.14  8.7   84.0        52.0  ...  0.758000  6.534660    0.06211  Suitable
1  7.70  8.8  110.0        76.0  ...  0.196062  8.138620    0.00960  Suitable
2  7.60  7.5   75.0        44.0  ...  0.298875  3.855625    0.01280  Suitable
3  8.20  9.1   76.0        56.0  ...  0.299590  2.238750    0.01536  Suitable
4  7.31  7.3   84.0        52.0  ...  0.106000  5.600000    0.01000  Suitable

[5 rows x 15 columns]

In [11]:
X = data.drop(['WQC'], axis=1)
Y = data['WQC']

Y = Y.map({'Suitable':0, 'Unsuitable':1})

In [12]:
# splitting the data into train and test set, we are using 20% of the data as test data
x_train, x_test, y_train, y_test = train_test_split(X.values, Y.values, test_size=0.2, stratify=Y)

In [13]:
# we will use VotingClassifier from sklearn.ensemble
from sklearn.ensemble import VotingClassifier

# create the base mmodels, we will train 5 classifiers(Decision Tree, Support Vector Machine, Logistic regression
# K-Nearest Neighbor and Naive Bayes)
dt = DecisionTreeClassifier()
svc = SVC()
lr = LogisticRegression()
knn = KNeighborsClassifier()
nb = GaussianNB()

# fitting the base models on the training data
dt.fit(x_train, y_train)
svc.fit(x_train, y_train)
lr.fit(x_train, y_train)
knn.fit(x_train, y_train)
nb.fit(x_train, y_train)

# testing accuracy of each of the base models
print(f'Decision Tree Accuracy: {accuracy_score(y_test, dt.predict(x_test))}')
print(f'Support Vector Machine Accuracy: {accuracy_score(y_test, svc.predict(x_test))}')
print(f'Logistic Regression Accuracy: {accuracy_score(y_test, lr.predict(x_test))}')
print(f'KNN Accuracy: {accuracy_score(y_test, knn.predict(x_test))}')
print(f'Naive Bayes Accuracy: {accuracy_score(y_test, nb.predict(x_test))}')

# now lets train the voting classifier
vc = VotingClassifier(estimators=[('dt', dt), ('svc', svc), ('lr', lr), ('knn', knn), ('nb', nb)])
vc.fit(x_train, y_train)
print(f'Voting Classifier Accuracy: {accuracy_score(y_test, vc.predict(x_test))}')

Decision Tree Accuracy: 0.979381443298969
Support Vector Machine Accuracy: 0.9484536082474226
Logistic Regression Accuracy: 0.9484536082474226
KNN Accuracy: 0.9587628865979382
Naive Bayes Accuracy: 0.8969072164948454
Voting Classifier Accuracy: 0.9587628865979382

In [14]:
class RandomForest:
    # intializing the required parameters
    # max_depth is default 30 to ensure a low bias, high variance model
    # col_sample is 0.5 as default to use only 50% of the columns to train base model
    # row_sample is 0.5 as default to use only 50% of rows to train base model
    def __init__(self, n_estimators=10, max_depth=30, col_sample=0.5, row_sample=0.5):
        self.n_estimators = n_estimators
        self.max_depth = max_depth
        self.col_sample = col_sample
        self.row_sample = row_sample

    def fit(self, X, Y):
        # these lists are used to keep track of the base models and their corresponding columns used to train them
        self.estimators = []
        self.col_samples = []
        # threshold row number and column number to be used
        row_thresh = int(X.shape[0]*self.row_sample)
        col_thresh = int(X.shape[1]*self.col_sample)

        # looping through the no. of estimators to be used
        for i in range(self.n_estimators):
            # building a base classifier
            clf = DecisionTreeClassifier(max_depth=self.max_depth)
            
            # creating random row samples
            row_indices = np.arange(X.shape[0])
            np.random.shuffle(row_indices)
            row_indices = row_indices[:row_thresh]
            
            # creating random column samples
            col_indices = np.arange(X.shape[1])
            np.random.shuffle(col_indices)
            col_indices = col_indices[:col_thresh]
            
            # extracting the random row and column samples
            X_sample = X[row_indices]
            Y_sample = Y[row_indices]
            X_sample = X_sample[:, col_indices]
            
            # fitting the base model on the radomly sampled data
            clf.fit(X_sample, Y_sample)
            
            # adding the model and corresponding column indices to use them later
            self.estimators.append(clf) 
            self.col_samples.append(col_indices)

    def predict(self, X):
        outputs = []
        
        # looping through the test data
        for x in X:
            out = []
            # using each base model and their corresponding columns to predict the test data
            for estimator, col_sample in zip(self.estimators, self.col_samples):
                x_sample = x[col_sample]
                out.append(estimator.predict([x_sample])[0])
            # taking the majority vote and adding it to the output array
            outputs.append(max(out, key=out.count))
        return np.array(outputs)

In [15]:
# Now lets see how to simple Random Forest Classifier performs
rclf = RandomForest(n_estimators=100)
rclf.fit(x_train, y_train)
y_pred = rclf.predict(x_test)
print(f'Accuracy: {accuracy_score(y_test, y_pred)}')
print(f'precision: {precision_score(y_test, y_pred)}')
print(f'Recall: {recall_score(y_test, y_pred)}')
print(f'F1 Score: {f1_score(y_test, y_pred)}')

Accuracy: 0.9484536082474226
precision: 0.5
Recall: 0.2
F1 Score: 0.28571428571428575

In [16]:
from sklearn.ensemble import RandomForestClassifier
# note this oob_score parameter
random_clf = RandomForestClassifier(oob_score=True)
random_clf.fit(x_train, y_train)
y_pred = random_clf.predict(x_test)
print(f'Accuracy: {accuracy_score(y_test, y_pred)}')
print(f'precision: {precision_score(y_test, y_pred)}')
print(f'Recall: {recall_score(y_test, y_pred)}')
print(f'F1 Score: {f1_score(y_test, y_pred)}')

Accuracy: 0.979381443298969
precision: 0.8
Recall: 0.8
F1 Score: 0.8000000000000002

In [17]:
print(f'Out of Bag score of Random Forest Classifier: {random_clf.oob_score_}')

Out of Bag score of Random Forest Classifier: 0.9742268041237113

In [18]:
for name, importance in zip(data.columns, random_clf.feature_importances_):
    print(f'{name}: {importance}')

pH: 0.04334415845483241
DO: 0.06937461669289906
TDS: 0.05911177851318735
Alkalinity: 0.038128698013771826
EC: 0.0514526930111095
Na: 0.050906740994832146
Ca: 0.06956289566971659
Mg: 0.025222933610502395
K: 0.042338806677893845
F: 0.056206227841893455
Cl: 0.059748024502501176
Nitrate: 0.04228239623507136
Sulphate: 0.037379429414907156
Phosphate: 0.35494060036688174

In [19]:
from sklearn.ensemble import ExtraTreesClassifier
extra_random_clf = ExtraTreesClassifier()
extra_random_clf.fit(x_train, y_train)
y_pred = extra_random_clf.predict(x_test)
print(f'Accuracy: {accuracy_score(y_test, y_pred)}')
print(f'precision: {precision_score(y_test, y_pred)}')
print(f'Recall: {recall_score(y_test, y_pred)}')
print(f'F1 Score: {f1_score(y_test, y_pred)}')

Accuracy: 0.9587628865979382
precision: 1.0
Recall: 0.2
F1 Score: 0.33333333333333337

In [20]:
class BoostingClassifier:
    # initializing the required parameters
    # n_estimators - default is 50, it is the number of base learners
    # max_depth - default is 1, it is the maximum depth of base learners
    # learning_rate - default is 0.5, it is used to limit the changes to the weights 
    # and to limit the value of alpha
    def __init__(self, n_estimators=50, max_depth=1, learning_rate=0.5):
        self.n_estimators = n_estimators
        self.max_depth = max_depth
        self.learning_rate = learning_rate
        self.trees = []
        self.alphas = []
        
    def fit(self, X, Y):
        # initializing the weights by 1/n
        weights = np.array([1/len(Y)]*len(Y))
        
        # looping through the no. of estimators
        for i in range(self.n_estimators):
            # building a base learner
            tree = DecisionTreeClassifier(max_depth=self.max_depth)
            
            # fitting the base learner with corresponding sample weights
            tree.fit(X, Y, sample_weight=weights)
            
            # adding the base learner to the list of base learners
            self.trees.append(tree)
            
            # predicting the class labels with this weak base learner
            y_pred = tree.predict(X)
            
            # calculating error
            error = np.sum(weights * (y_pred!=Y).astype(np.int))/np.sum(weights)
            
            # calculating alpha by multiplying with the learning rate
            alpha = self.learning_rate*np.log((1-error)/error)
            
            # adding this alpha to the list of alphas
            self.alphas.append(alpha)
            
            # updating the weights exponentially for the misclassified samples
            weights = weights * np.exp(alpha * (y_pred!=Y).astype(np.int))
    
    def predict(self, X):
        predictions = []
        
        # looping through all the alphas and the base models
        for alpha, tree in zip(self.alphas, self.trees):
            # multiplying alpha with the predictions of a base model
            y_pred = alpha * tree.predict(X)
            
            # adding this prediction to the list of predictions
            predictions.append(y_pred)
            
        # only the sign of the predictions will be required
        return  np.sign(np.sum(predictions, axis=0))

In [21]:
gclf = BoostingClassifier()
gclf.fit(x_train, y_train)
y_pred = gclf.predict(x_test)
print(f'Accuracy: {accuracy_score(y_test, y_pred)}')
print(f'precision: {precision_score(y_test, y_pred)}')
print(f'Recall: {recall_score(y_test, y_pred)}')
print(f'F1 Score: {f1_score(y_test, y_pred)}')

Accuracy: 0.05154639175257732
precision: 0.05154639175257732
Recall: 1.0
F1 Score: 0.0980392156862745

In [22]:
from sklearn.ensemble import AdaBoostClassifier
adaboost_clf = AdaBoostClassifier()
adaboost_clf.fit(x_train, y_train)
y_pred = adaboost_clf.predict(x_test)
print(f'Accuracy: {accuracy_score(y_test, y_pred)}')
print(f'precision: {precision_score(y_test, y_pred)}')
print(f'Recall: {recall_score(y_test, y_pred)}')
print(f'F1 Score: {f1_score(y_test, y_pred)}')

Accuracy: 0.979381443298969
precision: 0.8
Recall: 0.8
F1 Score: 0.8000000000000002

In [23]:
from sklearn.ensemble import GradientBoostingClassifier
gradboost_clf = GradientBoostingClassifier()
gradboost_clf.fit(x_train, y_train)
y_pred = gradboost_clf.predict(x_test)
print(f'Accuracy: {accuracy_score(y_test, y_pred)}')
print(f'precision: {precision_score(y_test, y_pred)}')
print(f'Recall: {recall_score(y_test, y_pred)}')
print(f'F1 Score: {f1_score(y_test, y_pred)}')

Accuracy: 0.979381443298969
precision: 0.8
Recall: 0.8
F1 Score: 0.8000000000000002

In [24]:
from xgboost import XGBClassifier
xgb_clf = XGBClassifier()
xgb_clf.fit(x_train, y_train)
y_pred = xgb_clf.predict(x_test)
print(f'Accuracy: {accuracy_score(y_test, y_pred)}')
print(f'precision: {precision_score(y_test, y_pred)}')
print(f'Recall: {recall_score(y_test, y_pred)}')
print(f'F1 Score: {f1_score(y_test, y_pred)}')

Accuracy: 0.9896907216494846
precision: 0.8333333333333334
Recall: 1.0
F1 Score: 0.9090909090909091

In [25]:
from mlxtend.classifier import StackingClassifier
# building the base models
knn = KNeighborsClassifier()
rf = RandomForestClassifier()
nb = GaussianNB()
# Logistic Regression model will be used as the Meta Classifier
lr = LogisticRegression()
stacking_clf = StackingClassifier(classifiers=[knn, rf, nb], meta_classifier=lr)
# looping through the  classifiers and taking a look at how they are performing
for name, clf in zip(['KNN', 'Random Forest', 'Naive Bayes', 'Stacking Classifier'], [knn, rf, nb, stacking_clf]):
    clf.fit(x_train, y_train)
    y_pred = clf.predict(x_test)
    print(f'Accuracy of {name}: {accuracy_score(y_test, y_pred)}')

Accuracy of KNN: 0.9587628865979382
Accuracy of Random Forest: 0.9690721649484536
Accuracy of Naive Bayes: 0.8969072164948454
Accuracy of Stacking Classifier: 0.979381443298969